name: CI

on:
 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: '.'

      - name: Print current directory
        run: pwd

      - name: List files in current directory
        run: ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd personal-test-data-generator
          npm install

      - name: Install dependencies
        run: |
          cd personal-test-data-generator
          npm install
        env:
          DB_HOST: 'localhost'
          DB_USER: 'root'
          DB_PASSWORD: 'password'
          DB_NAME: 'testdb'
          DB_PORT: '3306'

      - name: Wait for MySQL to be ready
        run: |
          for i in {30..0}; do
            if mysqladmin ping -h localhost -P 3306 --silent; then
              echo "MySQL is ready!"  
              break
            fi
              echo "MySQL is not ready, sleeping..."
              sleep 1
          done
          if [ "$i" = 0 ]; then
            echo 'MySQL did not start after 30 seconds'
            exit 1
          fi

      - name: Set up database schema and seed data
        working-directory: personal-test-data-generator
        run: |
          mysql -h localhost -P 3306 -u root -ppassword testdb < scripts/schema.sql # if this dosnt work change scripts to db
          mysql -h localhost -P 3306 -u root -ppassword testdb < scripts/seed.data.sql

      - name: Run tests
        run: |
          cd personal-test-data-generator
          npm test
        env:
          DB_HOST: 'localhost'
          DB_USER: 'root'
          DB_PASSWORD: 'password'
          DB_NAME: 'testdb'
          DB_PORT: '3306'
